- hosts: all
  vars:
    ansible_user: root
  tasks:
    - name: install sudo
      package:
        name: sudo
        state: installed

    - name: create mocops user
      user:
        name: mocops
        shell: /bin/bash

    - name: create sudo config for mocops user
      copy:
        content: |
          mocops ALL=(ALL) NOPASSWD: ALL
        dest: /etc/sudoers.d/mocops
        owner: root
        group: root
        mode: "0440"

    - name: create fake crontab
      copy:
        dest: /etc/crontab
        content: |
          SHELL=/bin/bash
          PATH=/sbin:/bin:/usr/sbin:/usr/bin
          MAILTO=root

          # For details see man 4 crontabs

          # Example of job definition:
          # .---------------- minute (0 - 59)
          # |  .------------- hour (0 - 23)
          # |  |  .---------- day of month (1 - 31)
          # |  |  |  .------- month (1 - 12) OR jan,feb,mar,apr ...
          # |  |  |  |  .---- day of week (0 - 6) (Sunday=0 or 7) OR sun,mon,tue,wed,thu,fri,sat
          # |  |  |  |  |
          # *  *  *  *  * user-name  command to be executed

          */5 * * * * root /root/checkdb
          */5 * * * * root docker ps|grep massopen &>/dev/null || /etc/scripts/firewall

    - name: create /etc/cron.daily directory
      file:
        path: /etc/cron.daily
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: create fake blockipupd script
      copy:
        dest: /etc/cron.daily/blockipupd
        content: |
          #!/bin/sh

          echo this is a test
